# Generated by Django 3.0 on 2021-07-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etiqette', '0002_auto_20210730_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etiqette.Cinema'),
            preserve_default=False,
        ),
    ]
