# Generated by Django 3.0 on 2021-07-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiqette', '0003_session_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cost',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
